name: generate daily words

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: gen words
        run: python picker.py

      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[automated] generate words for today"
          branch: main
          file_pattern: puzzle.txt
          
          commit_user_name: "word generation bot"
          commit_user_email: "actions@github.com"
